# Generated by Django 5.1.6 on 2025-02-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
